# Generated by Django 6.0.2 on 2026-03-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_address_country_remove_address_house_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
