# Generated by Django 6.0.2 on 2026-03-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_image_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card / Netbanking'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PREPARING', max_length=20),
        ),
    ]
